### ISSUE TITLE
Campaign-Description sollte keine Null Werte erlauben

### ISSUE THREAD

**Issue by Wetzu** [TheMokko/CampaignCreator#1]
Wenn in der Description der Kampagne Null-Werte sind, bleibt die Overview Seite im Rendering hängen

Lösungen:

- Im Rendering Zugriff auf Beschreibung gegen NULL-Werte prüfen
- Im Erstellen Dialog zum Pflichtfeld machen
- In der Datenbank keine NULL-Werte hier erlauben (Db muss gelöscht werden)

**Comment by TheMokko** [comment]
Leere Beschreibungen sind noch zulässig, da diese nicht immer erforderlich sein soll. Abfragen auf Null-Werte beim editieren und erstellen werden nun überprüft.
