### ISSUE TITLE
Target-URL Länge

### ISSUE THREAD

**Issue by Wetzu** [TheMokko/CampaignCreator#2]
Die Target-URL länge wird im Moment in der DB auf 100 Zeichen begrenzt.
Beim Verwenden einer zu längen URL wird keine Campaign angelegt, der User wird wieder auf die Übersichtsseite geleitet, kein Fehler wird ausgegeben

Lösung:

- Anpassen der Datenbank
- Validierung der Benutzereingabe
- Campaign Creation auf Sucess prüfen

**Comment by TheMokko** [comment]
Datenbank wurde angepasst und Status über die Erstellung nun ausgegeben
